# Основные настройки
[general]
email = "alla_bobrova.31@mail.ru"
showWarningOnDirectExecution = true

# Настройки кэширования
[caching]
enabled = true

# Настройки сервера
[server]
enableCORS = true
enableXsrfProtection = true
