name: Deploy Streamlit App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      working-directory: ${{ github.workspace }}
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt

    - name: Show contents of app directory
      run: ls -l ${{ github.workspace }}/app

    - name: Before running Streamlit app
      run: echo "Before running Streamlit app"

    - name: Run Streamlit app
      run: streamlit run app/github_page.py

    - name: After running Streamlit app
      run: echo "After running Streamlit app"

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./app
