name: Generate README

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate_readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.name "alla-bobrova"
        git config --global user.email "your-email@example.com"

    - name: Generate tree
      run: |
        echo "# Repository Tree" > README.md
        echo "" >> README.md
        find . -type f ! -path './.github/*' ! -path './node_modules/*' ! -name 'README.md' | sed -e 's/^\.\///' | awk -F/ '{print $NF}' | sort | sed -e 's/^/├── /' >> README.md

    - name: Display changes
      run: cat README.md

    - name: Commit changes
      run: |
        git add README.md
        git diff --cached --quiet || git commit -m "Update README with repository tree"

    - name: Push changes with token
      if: github.event_name == 'push'
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        git push https://alla-bobrova:${{ secrets.GH_TOKEN }}@github.com/alla-bobrova/Synchronization.git HEAD:main

