name: Generate README

on:
  push:
    branches:
      - main

jobs:
  generate_readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.name "alla-bobrova"
        git config --global user.email "alla_bobrova.31@mail.ru"

    - name: Generate tree
      run: |
        echo "# Repository Tree" > README.md
        echo "" >> README.md
        tree -a -I '.github|node_modules' >> README.md

    - name: Commit and push changes
      run: |
        git add README.md
        git commit -m "Generate README with repository tree"
        git remote add origin_with_token https://alla-bobrova:${{ secrets.GH_TOKEN }}@github.com/alla-bobrova/Synchronization.git
        git push origin_with_token main
